Update exclude section.
Update the configuration to work with Jekyll 3.3.0 and above.
https://jekyllrb.com/docs/troubleshooting/#configuration-problems
says:

    Note: From v3.3.0 onward, Jekyll does not process node_modules and
    certain subdirectories within vendor, by default. But, by having
    an exclude: array defined explicitly in the config file overrides
    this default setting, which results in some users to encounter an
    error in building the site, with the following error message:

        ERROR: YOUR SITE COULD NOT BE BUILT:
        ------------------------------------
        Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>':
        Document 'vendor/bundle/gems/jekyll-3.4.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb'
        does not have a valid date in front matter.